// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @react-native-async-storage/async-storage
#include <winrt/ReactNativeAsyncStorage.h>

// Includes from @react-native-clipboard/clipboard
#include <winrt/NativeClipboard.h>

// Includes from react-native-blob-util
#include <winrt/ReactNativeBlobUtil.h>

// Includes from react-native-document-picker
#include <winrt/ReactNativeDocumentPicker.h>

// Includes from react-native-pdf
#include <winrt/RCTPdf.h>

// Includes from react-native-screens
#include <winrt/RNScreens.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @react-native-async-storage/async-storage
    packageProviders.Append(winrt::ReactNativeAsyncStorage::ReactPackageProvider());
    // IReactPackageProviders from @react-native-clipboard/clipboard
    packageProviders.Append(winrt::NativeClipboard::ReactPackageProvider());
    // IReactPackageProviders from react-native-blob-util
    packageProviders.Append(winrt::ReactNativeBlobUtil::ReactPackageProvider());
    // IReactPackageProviders from react-native-document-picker
    packageProviders.Append(winrt::ReactNativeDocumentPicker::ReactPackageProvider());
    // IReactPackageProviders from react-native-pdf
    packageProviders.Append(winrt::RCTPdf::ReactPackageProvider());
    // IReactPackageProviders from react-native-screens
    packageProviders.Append(winrt::RNScreens::ReactPackageProvider());
}

}
